- hosts: all
  become: true
  vars_files:
    - ../roles/kernel_tuning/vars.yml   # load tuning parameters
  tasks:
    - include_tasks: ../roles/kernel_tuning/tasks.yml
  handlers:
    - include_tasks: ../roles/kernel_tuning/handlers.yml
